# Generated by Django 4.2.2 on 2023-07-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
