# Generated by Django 4.2.2 on 2023-07-29 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0006_alter_userrolemodel_policies_and_more'),
        ('dynamic_models', '0004_testmodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField()),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.userrolemodel')),
            ],
        ),
    ]
