# Generated by Django 4.2.2 on 2023-07-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0006_framemodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel1',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
