# Generated by Django 4.2.2 on 2023-07-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0007_testmodel1_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
