# Generated by Django 4.2.2 on 2023-07-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0006_alter_userrolemodel_policies_and_more'),
        ('dynamic_models', '0008_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='framemodel',
            name='many_test',
            field=models.ManyToManyField(to='appauth.userrolemodel'),
        ),
    ]
