# Generated by Django 4.2.2 on 2023-07-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0010_address_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='framemodel',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
