# Generated by Django 4.2.4 on 2023-08-24 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_a1', models.CharField(max_length=50)),
                ('field_a2', models.IntegerField()),
                ('field_a3', models.BooleanField()),
                ('field_a4', models.DateField()),
                ('field_a5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field_a6', models.TextField()),
                ('field_a7', models.EmailField(max_length=254)),
                ('field_a8', models.URLField()),
                ('field_a9', models.ImageField(upload_to='images/')),
                ('field_a10', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_b1', models.CharField(max_length=50)),
                ('field_b2', models.IntegerField()),
                ('field_b3', models.BooleanField()),
                ('field_b4', models.DateField()),
                ('field_b5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field_b6', models.TextField()),
                ('field_b7', models.EmailField(max_length=254)),
                ('field_b8', models.URLField()),
                ('field_b9', models.ImageField(upload_to='images/')),
                ('field_b10', models.FloatField()),
                ('model_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadtest_3.modela')),
            ],
        ),
        migrations.CreateModel(
            name='ModelC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_c1', models.CharField(max_length=50)),
                ('field_c2', models.IntegerField()),
                ('field_c3', models.BooleanField()),
                ('field_c4', models.DateField()),
                ('field_c5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field_c6', models.TextField()),
                ('field_c7', models.EmailField(max_length=254)),
                ('field_c8', models.URLField()),
                ('field_c9', models.ImageField(upload_to='images/')),
                ('field_c10', models.FloatField()),
                ('model_b', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loadtest_3.modelb')),
            ],
        ),
        migrations.CreateModel(
            name='AggBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadtest_3.aggauthor')),
            ],
        ),
    ]
