# Generated by Django 4.2.6 on 2023-12-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectstore',
            name='object_uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
