# Generated by Django 4.2.6 on 2023-12-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_store', '0002_alter_objectstore_object_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectstore',
            name='object_uuid',
            field=models.UUIDField(editable=False),
        ),
    ]
