# Generated by Django 4.2.5.dev20230804160846 on 2023-08-25 07:15

from django.db import migrations


def create_default_userroles(apps, schema_editor):
    """
    creates AnonymousUsers & SystemUsers roles 
    """
    user_role_model = apps.get_model('appauth', 'UserRoleModel')
    user_role_model.objects.create(name='AnonymousUsers', is_default=True)
    user_role_model.objects.create(name='SystemUsers', is_default=True)



class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_userroles),
    ]
