# Generated by Django 4.2.11 on 2024-09-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0006_appusermodel_app_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusermodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
