# Generated by Django 4.2.15 on 2025-04-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0007_appuserauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserauthtoken',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
