# Generated by Django 4.2.16 on 2025-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0007_appuserauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusermodel',
            name='auth_config',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='userrolemodel',
            name='auth_config',
            field=models.JSONField(default={}),
        ),
    ]
