exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "docs",
    "tests",
    "migrations",
    "frontend",
]

target-version = "py311"
line-length = 88

lint.ignore = ["F405", "F841"]

[lint.isort.sections]
"django" = ["django"]
"zango" = ["zango"]

[lint.isort]
lines-after-imports = 2
lines-between-types = 1
section-order = ["future", "standard-library", "third-party", "django", "zango", "local-folder", ]
