version: '3.8'

services:
 postgres:
   image: postgres
   environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_PORT: ${POSTGRES_PORT}
     PROJECT_NAME: ${PROJECT_NAME}
   ports:
     - "5432:5432"
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
   volumes: 
     - dev_db:/var/lib/postgresql/data

 app:
   build:
     context: .
     dockerfile: dev.dockerfile
   ports:
     - "8000:8000"
   depends_on:
     postgres:
       condition: service_healthy
   environment:
     PROJECT_NAME: ${PROJECT_NAME}
     SERVER: runserver
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_HOST: ${POSTGRES_HOST}
     POSTGRES_PORT: ${POSTGRES_PORT}
     PLATFORM_USERNAME: ${PLATFORM_USERNAME}
     PLATFORM_USER_PASSWORD: ${PLATFORM_USER_PASSWORD}
     AWS_SECRET_ACCESS_KEY: ${PACKAGE_REPO_AWS_SECRET_ACCESS_KEY}
     AWS_ACCESS_KEY_ID: ${PACKAGE_REPO_AWS_ACCESS_KEY_ID}
     ENV: dev
   volumes:
     - .:/zelthy/

volumes:
  dev_db: