version: '3.8'

services:
 postgres:
   image: postgres
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: zelthy3pass
     POSTGRES_DB: zelthy1
     PROJECT_NAME: ${PROJECT_NAME}
   ports:
     - "5432:5432"
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

 app:
   build:
     context: .
     dockerfile: server.dockerfile
     args:
       - PROJECT_NAME=${PROJECT_NAME}
   ports:
     - "8000:8000"
   depends_on:
     postgres:
       condition: service_healthy
   environment:
     SERVER: ${SERVER}
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: zelthy3pass
     POSTGRES_DB: zelthy1
     POSTGRES_HOST: postgres
     POSTGRES_PORT: 5432
     PROJECT_NAME: ${PROJECT_NAME}
     PLATFORM_USERNAME: ${PLATFORM_USERNAME}
     PLATFORM_USER_PASSWORD: ${PLATFORM_USER_PASSWORD}
     AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
     AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
   volumes: 
     - .:/zelthy/
