version: '3.8'

services:
 postgres:
   image: postgres
   environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_PORT: ${POSTGRES_PORT}
     PROJECT_NAME: ${PROJECT_NAME}
   ports:
     - "5432:5432"
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
   volumes: 
     - prod_db:/var/lib/postgresql/data

 app:
   build:
     context: .
     dockerfile: prod.dockerfile
     args:
       - PROJECT_NAME=${PROJECT_NAME}
   ports:
     - "8000:8000"
   depends_on:
     postgres:
       condition: service_healthy
   environment:
     SERVER: gunicorn
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_HOST: ${POSTGRES_HOST}
     POSTGRES_PORT: ${POSTGRES_PORT}
     PROJECT_NAME: ${PROJECT_NAME}
     PLATFORM_USERNAME: ${PLATFORM_USERNAME}
     PLATFORM_USER_PASSWORD: ${PLATFORM_USER_PASSWORD}
     PLATFORM_REPO_AWS_SECRET_ACCESS_KEY: ${PLATFORM_REPO_AWS_SECRET_ACCESS_KEY}
     PLATFORM_REPO_AWS_ACCESS_KEY_ID: ${PLATFORM_REPO_AWS_ACCESS_KEY_ID}
     ENV: prod
   volumes:
     - .:/zelthy/
  
 nginx:
   build:
     context: .
     dockerfile: config/Dockerfile
   ports:
    - "1443:1443"
   depends_on:
     - app
   environment:
     - PROJECT_NAME=${PROJECT_NAME}
  #  volumes:
  #    - ./${PROJECT_NAME}/static:/zelthy/${PROJECT_NAME}/static

volumes:
  prod_db: