# Generated by Django 4.2.16 on 2025-12-30 11:33

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zango.core.storage_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platformauth', '0002_platformusermodel_is_superadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZangoAdminCodeExecutionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('slug_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text="Example: 'flatpages/default.html'", max_length=100, verbose_name='name')),
                ('description', models.CharField(help_text='Template Description', max_length=1000, verbose_name='Description')),
                ('code', models.TextField(blank=True, verbose_name='content')),
                ('artifact', zango.core.storage_utils.ZFileField(blank=True, null=True, upload_to=zango.core.storage_utils.RandomUniqueFileName, validators=[zango.core.storage_utils.validate_file_extension], verbose_name='ZangoAdminCodeExecution Artifact')),
                ('execution_history', models.JSONField(blank=True, default=[], null=True)),
                ('output_file', zango.core.storage_utils.ZFileField(blank=True, null=True, upload_to=zango.core.storage_utils.RandomUniqueFileName, validators=[zango.core.storage_utils.validate_file_extension], verbose_name='ZangoAdminCodeExecution Output')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platformauth.platformusermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
