# Generated by Django 4.2.3 on 2023-08-08 12:45

from django.db import migrations, models
import django.db.models.deletion
import workspaces.Tenant3.foreign_key.models
import zelthy3.backend.apps.tenants.dynamic_models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=10)),
                ('d', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(max_length=10)),
                ('a', zelthy3.backend.apps.tenants.dynamic_models.fields.ZForeignKey(default=workspaces.Tenant3.foreign_key.models.get_foo, on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='dynamic_models.foo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
