# Generated by Django 4.2.3 on 2023-08-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0003_manualprimarykey_place_school_target_pointer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='restaurants',
        ),
    ]
