# Generated by Django 4.2.3 on 2023-08-09 06:11

from django.db import migrations, models
import django.db.models.deletion
import zelthy3.backend.apps.tenants.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0006_domain_family_genus_kingdom_klass_topping_species_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent2',
            fields=[
                ('id2', models.AutoField(primary_key=True, serialize=False)),
                ('name2', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserStatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child1',
            fields=[
                ('parent2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='dynamic_models.parent2')),
                ('parent1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.parent1')),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.parent1', 'dynamic_models.parent2'),
        ),
        migrations.CreateModel(
            name='Child2',
            fields=[
                ('parent1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.parent1')),
                ('value', models.IntegerField()),
                ('parent2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.parent2')),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.parent1',),
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dynamic_models.ouser')),
                ('posts', models.IntegerField()),
                ('results', zelthy3.backend.apps.tenants.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.userstatresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.ouser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_models.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('previous_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_item', to='dynamic_models.linkedlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvancedUserStat',
            fields=[
                ('userstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.userstat')),
                ('karma', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.userstat',),
        ),
        migrations.CreateModel(
            name='Child3',
            fields=[
                ('child2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.child2')),
                ('value3', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.child2',),
        ),
        migrations.CreateModel(
            name='Child4',
            fields=[
                ('child1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.child1')),
                ('value4', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.child1',),
        ),
        migrations.CreateModel(
            name='StatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.IntegerField()),
                ('base_stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.userstat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
