# Generated by Django 4.2.3 on 2023-08-09 08:37

from django.db import migrations, models
import django.db.models.deletion
import zelthy3.backend.apps.tenants.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0008_remove_child1_parent1_ptr_remove_child1_parent2_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedUserStat',
            fields=[
                ('userstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.userstat')),
                ('karma', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.userstat',),
        ),
        migrations.CreateModel(
            name='Child1',
            fields=[
                ('parent2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='dynamic_models.parent2')),
                ('parent1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.parent1')),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.parent1', 'dynamic_models.parent2'),
        ),
        migrations.CreateModel(
            name='Child2',
            fields=[
                ('parent1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.parent1')),
                ('value', models.IntegerField()),
                ('parent2', zelthy3.backend.apps.tenants.dynamic_models.fields.ZOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.parent2')),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.parent1',),
        ),
        migrations.AlterField(
            model_name='linkedlist',
            name='previous_item',
            field=zelthy3.backend.apps.tenants.dynamic_models.fields.ZOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_item', to='dynamic_models.linkedlist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=zelthy3.backend.apps.tenants.dynamic_models.fields.ZOneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_models.image'),
        ),
        migrations.AlterField(
            model_name='statdetails',
            name='base_stats',
            field=zelthy3.backend.apps.tenants.dynamic_models.fields.ZOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.userstat'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=zelthy3.backend.apps.tenants.dynamic_models.fields.ZOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.ouser'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='user',
            field=zelthy3.backend.apps.tenants.dynamic_models.fields.ZOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dynamic_models.ouser'),
        ),
        migrations.CreateModel(
            name='Child3',
            fields=[
                ('child2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.child2')),
                ('value3', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.child2',),
        ),
        migrations.CreateModel(
            name='Child4',
            fields=[
                ('child1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.child1')),
                ('value4', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.child1',),
        ),
    ]
