# Generated by Django 4.2.3 on 2023-08-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0009_advanceduserstat_child1_child2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkedList',
        ),
    ]
