# Generated by Django 4.2.3 on 2023-08-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0010_delete_linkedlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child1',
            name='parent1_ptr',
        ),
        migrations.RemoveField(
            model_name='child1',
            name='parent2_ptr',
        ),
        migrations.RemoveField(
            model_name='child2',
            name='parent1_ptr',
        ),
        migrations.RemoveField(
            model_name='child2',
            name='parent2',
        ),
        migrations.RemoveField(
            model_name='child3',
            name='child2_ptr',
        ),
        migrations.RemoveField(
            model_name='child4',
            name='child1_ptr',
        ),
        migrations.DeleteModel(
            name='AdvancedUserStat',
        ),
        migrations.DeleteModel(
            name='Child1',
        ),
        migrations.DeleteModel(
            name='Child2',
        ),
        migrations.DeleteModel(
            name='Child3',
        ),
        migrations.DeleteModel(
            name='Child4',
        ),
    ]
