# Generated by Django 4.2.3 on 2023-08-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0012_a_c_datapoint_uniquenumber_uniquenumberchild_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='D',
        ),
    ]
