# Generated by Django 4.2.2 on 2023-07-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrolemodel',
            old_name='versions',
            new_name='config',
        ),
    ]
