# Generated by Django 4.2.2 on 2023-07-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_policymodel_description_policygroupmodel'),
        ('appauth', '0002_rename_versions_userrolemodel_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolemodel',
            name='policies',
            field=models.ManyToManyField(related_name='role_policies', to='permissions.policymodel'),
        ),
        migrations.AddField(
            model_name='userrolemodel',
            name='policy_groups',
            field=models.ManyToManyField(related_name='role_policy_groups', to='permissions.policygroupmodel'),
        ),
    ]
