# Generated by Django 4.2.2 on 2023-07-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_rename_config_policymodel_statement'),
        ('appauth', '0003_userrolemodel_policies_userrolemodel_policy_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusermodel',
            name='policies',
            field=models.ManyToManyField(related_name='user_policies', to='permissions.policymodel'),
        ),
        migrations.AddField(
            model_name='appusermodel',
            name='policy_groups',
            field=models.ManyToManyField(related_name='user_policy_groups', to='permissions.policygroupmodel'),
        ),
    ]
