# Generated by Django 4.2.2 on 2023-07-15 04:49

from django.db import migrations, models


def create_default_objects(apps, schema_editor):
    klass = apps.get_model('appauth', 'UserRoleModel')
    klass.objects.create(name="AnonymousUsers", is_default=True)
    klass.objects.create(name="SystemUsers", is_default=False)
    return



class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0004_appusermodel_policies_appusermodel_policy_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolemodel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_default_objects),
    ]
