# Generated by Django 4.2.2 on 2023-07-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_policymodel_expiry'),
        ('appauth', '0005_userrolemodel_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolemodel',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='role_policies', to='permissions.policymodel'),
        ),
        migrations.AlterField(
            model_name='userrolemodel',
            name='policy_groups',
            field=models.ManyToManyField(blank=True, related_name='role_policy_groups', to='permissions.policygroupmodel'),
        ),
    ]
