# Generated by Django 4.2.5 on 2023-10-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policymodel",
            name="type",
            field=models.CharField(
                choices=[("system", "SYSTEM"), ("user", "USER")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="policymodel",
            name="expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
