# Generated by Django 4.2.5 on 2023-10-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policymodel",
            name="expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
