# Generated by Django 4.2.6 on 2023-10-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policymodel',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
