# Generated by Django 4.2.5.dev20230804160846 on 2023-09-08 10:08

from django.db import migrations, models
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FramesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('user_role', zelthy.apps.dynamic_models.fields.ZOneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='frame', to='appauth.userrolemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
