# Generated by Django 4.2.2 on 2023-08-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instance',
        ),
    ]
