# Generated by Django 4.2.5.dev20230804160846 on 2023-09-21 13:17

from django.db import migrations
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0002_default_user_roles'),
        ('dynamic_models', '0002_fhirpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirpatient',
            name='user_role',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.userrolemodel'),
        ),
    ]
