# Generated by Django 4.2.2 on 2023-08-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0002_delete_instance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address1',
        ),
    ]
