# Generated by Django 4.2.2 on 2023-08-05 17:58

from django.db import migrations, models
import django.db.models.deletion
import zelthy3.backend.apps.tenants.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0007_userrolemodel_temp_field'),
        ('dynamic_models', '0003_delete_address1'),
    ]

    operations = [
        migrations.CreateModel(
            name='FramesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField()),
                ('user_role', zelthy3.backend.apps.tenants.dynamic_models.fields.ZOneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='frame', to='appauth.userrolemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
