# Generated by Django 4.2.2 on 2023-08-06 12:09

from django.db import migrations, models
import django.db.models.deletion
import zelthy3.backend.apps.tenants.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0007_userrolemodel_temp_field'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dynamic_models', '0005_programmodel_programapplicationvalidator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrudConfigurationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_config', models.JSONField(null=True)),
                ('form_config', models.JSONField(null=True)),
                ('model', zelthy3.backend.apps.tenants.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('role', zelthy3.backend.apps.tenants.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appauth.userrolemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
