# Generated by Django 4.2.2 on 2023-08-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0007_framesmodel_user_role_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framesmodel',
            name='user_role_fk',
        ),
    ]
