# Generated by Django 4.2.2 on 2023-08-08 06:51

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zelthy3.backend.apps.tenants.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('appauth', '0007_userrolemodel_temp_field'),
        ('dynamic_models', '0008_remove_framesmodel_user_role_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='framesmodel',
            name='chars',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=50, null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='framesmodel',
            name='timestamp',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='framesmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.CreateModel(
            name='CrudConfigurationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_config', models.JSONField(null=True)),
                ('form_config', models.JSONField(null=True)),
                ('model', zelthy3.backend.apps.tenants.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('role', zelthy3.backend.apps.tenants.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appauth.userrolemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
