# Generated by Django 3.2 on 2023-07-12 06:14

from django.db import migrations, models
import zelthy3.backend.apps.tenants.datamodel.mixin
import zelthy3.backend.apps.tenants.datamodel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('label', models.CharField(max_length=100, unique=True, validators=[zelthy3.backend.apps.tenants.datamodel.models.validate_name], verbose_name='Label')),
                ('field_specs', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=300, verbose_name='model_description')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, zelthy3.backend.apps.tenants.datamodel.mixin.DynamicModelMixin),
        ),
    ]
