# Generated by Django 4.2.4 on 2023-09-08 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_rename_is_default_themesmodel_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="themesmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="themesmodel",
            name="created_by",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="themesmodel",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="themesmodel",
            name="modified_by",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
