# Generated by Django 4.2.11 on 2024-08-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprelease',
            name='last_git_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
