# Generated by Django 4.2.2 on 2023-07-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of the permission')),
                ('type', models.CharField(choices=[('view', 'View'), ('datamodel', 'DataModel'), ('user_access', 'User Access'), ('custom', 'Custom')], max_length=50, verbose_name='Type of the permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
