# Generated by Django 4.2.2 on 2023-07-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_policymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policymodel',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description of the policy'),
        ),
        migrations.CreateModel(
            name='PolicyGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name of the policy group')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description of the policy group')),
                ('policies', models.ManyToManyField(related_name='policy_groups', to='permissions.policymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
