# Generated by Django 4.2.2 on 2023-07-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_policymodel_description_policygroupmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policymodel',
            old_name='config',
            new_name='statement',
        ),
    ]
