# Generated by Django 4.2.2 on 2023-07-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_rename_config_policymodel_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymodel',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
