# Generated by Django 4.2.2 on 2023-07-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_policymodel_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
