# Generated by Django 4.2.16 on 2026-06-01 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogConnectorConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(help_text="Mirrors settings.ENV — e.g. 'local', 'staging', 'prod'.", max_length=32)),
                ('component', models.CharField(choices=[('app', 'App'), ('celery', 'Celery worker'), ('celery_beat', 'Celery beat')], max_length=16)),
                ('connector', models.CharField(choices=[('cloudwatch', 'AWS CloudWatch Logs')], max_length=32)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'platform_log_connector_config',
                'ordering': ['environment', 'component'],
                'indexes': [models.Index(fields=['environment', 'is_active'], name='platform_lo_environ_90ca6a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='logconnectorconfig',
            constraint=models.UniqueConstraint(fields=('environment', 'component'), name='platform_logs_unique_env_component'),
        ),
    ]
