# Generated by Django 4.2.16 on 2026-09-10 05:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('object_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('prompt', models.TextField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('trigger_kind', models.CharField(choices=[('ui', 'App Settings UI'), ('api', 'API'), ('resume', 'Resume / continue'), ('retry', 'Retry')], default='ui', max_length=16)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('syncing', 'Syncing'), ('success', 'Success'), ('partial', 'Completed with sync errors'), ('failed', 'Failed'), ('timeout', 'Timed out'), ('aborted', 'Aborted')], db_index=True, default='queued', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('abort_requested', models.BooleanField(default=False)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('agent_ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('effort', models.CharField(blank=True, default='', max_length=16)),
                ('permission_mode', models.CharField(blank=True, default='', max_length=32)),
                ('max_turns', models.PositiveIntegerField(blank=True, null=True)),
                ('max_budget_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('skill_name', models.CharField(blank=True, default='', max_length=128)),
                ('workspace_path', models.CharField(blank=True, default='', max_length=1024)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('result_subtype', models.CharField(blank=True, default='', max_length=32)),
                ('terminal_reason', models.CharField(blank=True, default='', max_length=64)),
                ('result_text', models.TextField(blank=True, default='')),
                ('num_turns', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_api_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('total_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('input_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cache_read_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cache_creation_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('model_usage', models.JSONField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=128)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_traceback', models.TextField(blank=True, default='')),
                ('api_error_status', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshot_path', models.CharField(blank=True, default='', max_length=1024)),
                ('snapshot_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('files_changed', models.JSONField(blank=True, null=True)),
                ('tool_use_counts', models.JSONField(blank=True, null=True)),
                ('post_steps', models.JSONField(blank=True, null=True)),
                ('requires_restart', models.BooleanField(default=False)),
                ('resumed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='agent_mode.agentrun')),
            ],
            options={
                'db_table': 'agent_mode_run',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('sys', 'Runner narration'), ('init', 'Session init'), ('assistant', 'Assistant text'), ('thinking', 'Thinking'), ('tool_use', 'Tool use'), ('tool_result', 'Tool result'), ('skill', 'Skill invocation'), ('user', 'User / tool feedback'), ('compact', 'Context compaction'), ('hook_deny', 'Blocked by policy'), ('post_step', 'Post-run step'), ('stdout', 'Subprocess stdout'), ('stderr', 'Subprocess stderr'), ('result', 'Result'), ('error', 'Error')], db_index=True, max_length=16)),
                ('level', models.CharField(choices=[('info', 'INFO'), ('warn', 'WARN'), ('err', 'ERROR'), ('sys', 'system')], default='info', max_length=8)),
                ('message', models.TextField(blank=True, default='')),
                ('tool_name', models.CharField(blank=True, default='', max_length=64)),
                ('tool_use_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('parent_tool_use_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_error', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agent_mode.agentrun')),
            ],
            options={
                'db_table': 'agent_mode_run_event',
                'ordering': ['run', 'seq'],
                'indexes': [models.Index(fields=['run', 'seq'], name='agent_mode__run_id_5e671e_idx'), models.Index(fields=['run', 'kind', 'seq'], name='agent_mode__run_id_b5b7b5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentrunevent',
            constraint=models.UniqueConstraint(fields=('run', 'seq'), name='agent_mode_event_unique_seq'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', '-queued_at'], name='agent_mode__status_03d88b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['-queued_at'], name='agent_mode__queued__0a1c80_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='agent_mode_single_active_run'),
        ),
    ]
