# Generated by Django 4.2.16 on 2026-09-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_mode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='test_users',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
