# Generated by Django 4.2.16 on 2026-09-12 02:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent_mode', '0002_agentrun_test_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('object_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('initial_prompt', models.TextField()),
                ('status', models.CharField(choices=[('gathering', 'Gathering requirements'), ('ready', 'Ready for review'), ('approved', 'Approved'), ('abandoned', 'Abandoned')], db_index=True, default='gathering', max_length=16)),
                ('spec_markdown', models.TextField(blank=True, default='')),
                ('spec_version', models.PositiveIntegerField(default=0)),
                ('session_id', models.CharField(blank=True, default='', max_length=128)),
                ('turns', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_thinking', models.BooleanField(default=False)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_by_label', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'agent_mode_requirement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentrunevent',
            name='phase',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('planning', 'Planning'), ('building', 'Building'), ('wiring', 'Wiring up'), ('applying', 'Applying changes'), ('users', 'Roles & test users'), ('done', 'Finished')], db_index=True, default='preparing', max_length=12),
        ),
        migrations.CreateModel(
            name='AgentRequirementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('spec_markdown', models.TextField()),
                ('source', models.CharField(choices=[('agent', 'Agent'), ('user', 'Edited by user')], default='agent', max_length=8)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agent_mode.agentrequirement')),
            ],
            options={
                'db_table': 'agent_mode_requirement_version',
                'ordering': ['requirement', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AgentRequirementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=12)),
                ('content', models.TextField(blank=True, default='')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('is_question', models.BooleanField(default=False)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_mode.agentrequirement')),
            ],
            options={
                'db_table': 'agent_mode_requirement_message',
                'ordering': ['requirement', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='agentrequirement',
            index=models.Index(fields=['status', '-created_at'], name='agent_mode__status_b5172c_idx'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='agent_mode.agentrequirement'),
        ),
        migrations.AddConstraint(
            model_name='agentrequirementversion',
            constraint=models.UniqueConstraint(fields=('requirement', 'version'), name='agent_mode_req_version_unique'),
        ),
        migrations.AddIndex(
            model_name='agentrequirementmessage',
            index=models.Index(fields=['requirement', 'seq'], name='agent_mode__require_3effe1_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentrequirementmessage',
            constraint=models.UniqueConstraint(fields=('requirement', 'seq'), name='agent_mode_req_msg_unique_seq'),
        ),
    ]
