# Generated by Django 4.2.4 on 2023-08-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=15, unique=True, verbose_name='Company code name')),
                ('full_name', models.CharField(max_length=100, unique=True, verbose_name='Company Legal Name')),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Company Logo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
