# Generated by Django 4.2.4 on 2023-08-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0002_companyaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logo/', verbose_name='Company Logo'),
        ),
    ]
