# Generated by Django 4.2.4 on 2023-08-25 09:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0003_alter_companyaccount_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(blank=True, max_length=25, verbose_name='Short Code of Program')),
                ('program_name', models.CharField(max_length=255, unique=True, verbose_name='Program Name')),
                ('description', models.TextField(blank=True, verbose_name='Program Description')),
                ('patient_eligibility', models.TextField(blank=True, max_length=2000)),
                ('program_eligibility', models.TextField(blank=True, max_length=2000)),
                ('extrafield1_char', models.CharField(blank=True, max_length=255, verbose_name='Extra Field1 Char')),
                ('extrafield2_char', models.CharField(blank=True, max_length=255, verbose_name='Extra Field2 Char')),
                ('extrafield3_char', models.CharField(blank=True, max_length=255, verbose_name='Extra Field3 Char')),
                ('extrafield1_boolean', models.BooleanField(default=False, verbose_name='Extra Field1 Boolean')),
                ('extrafield2_boolean', models.BooleanField(default=False, verbose_name='Extra Field2 Boolean')),
                ('extrafield3_boolean', models.BooleanField(default=False, verbose_name='Extra Field3 Boolean')),
                ('is_delivered_as_camp', models.BooleanField(default=False, verbose_name='Is the program delivered as camp')),
                ('program_delivered_through', models.CharField(blank=True, choices=[('hospital', 'Hospital'), ('doctor', 'Doctor')], max_length=50, verbose_name='Camp delivery mode')),
                ('jsonfield_extra1', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
