# Generated by Django 4.2.4 on 2023-08-28 05:51

from django.db import migrations, models
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0005_benefitsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Supply Chain Node Label')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('track_inventory', models.BooleanField(default=True, verbose_name='Track Inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenefitsSupplyChainNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', zelthy.apps.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.benefitsmodel')),
                ('scn_executor_nodes', zelthy.apps.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.supplychainnodes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
