# Generated by Django 4.2.4 on 2023-08-28 08:51

from django.db import migrations, models
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0007_dispensingoptionsmodel_skumodel_skutypes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsDispensingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', zelthy.apps.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.benefitsmodel')),
                ('dispensingoption', zelthy.apps.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.dispensingoptionsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
