# Generated by Django 4.2.4 on 2023-08-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0009_abstractpatient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractPatient',
        ),
    ]
