# Generated by Django 4.2.4 on 2023-08-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0013_remove_benefitsmodel_test_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitsmodel',
            name='name1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
    ]
