# Generated by Django 4.2.4 on 2023-08-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0016_remove_benefitsmodel_test_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractTempOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        # migrations.RemoveField(
        #     model_name='benefitsmodel',
        #     name='test_role',
        # ),
        migrations.CreateModel(
            name='TempOrderModel',
            fields=[
                ('abstracttempordermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_models.abstracttempordermodel')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
            bases=('dynamic_models.abstracttempordermodel',),
        ),
    ]
