# Generated by Django 4.2.4 on 2023-08-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0017_abstracttempordermodel_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='benefitsmodel',
        #     name='test_role',
        # ),
    ]
