# Generated by Django 4.2.4 on 2023-08-30 09:31

from django.db import migrations
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
        ('dynamic_models', '0018_remove_benefitsmodel_test_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitsmodel',
            name='test_role',
            field=zelthy.apps.dynamic_models.fields.ZOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appauth.userrolemodel'),
        ),
    ]
