# Generated by Django 4.2.4 on 2023-08-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0020_benefitsmodel_temp_role2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractTempModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
