# Generated by Django 4.2.4 on 2023-08-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0021_abstracttempmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractTempModel',
        ),
    ]
