# Generated by Django 4.2.4 on 2023-09-01 08:03

from django.db import migrations, models
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0022_delete_abstracttempmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='Doctor Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='benefitsmodel',
            options={'ordering': ['-short_code']},
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.doctormodel'),
        ),
    ]
