# Generated by Django 4.2.4 on 2023-09-01 09:51

from django.db import migrations, models
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0023_doctormodel_alter_benefitsmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255, verbose_name='City Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='city',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.citymode'),
        ),
    ]
