# Generated by Django 4.2.4 on 2023-09-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0024_citymode_doctormodel_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityMode',
            new_name='CityModel',
        ),
    ]
