# Generated by Django 4.2.4 on 2023-09-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0025_rename_citymode_citymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patient2',
        ),
    ]
