# Generated by Django 4.2.4 on 2023-09-05 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0026_rename_patient_patient2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient2',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='DoctorModel',
        ),
        migrations.DeleteModel(
            name='Patient2',
        ),
    ]
