# Generated by Django 4.2.4 on 2023-09-06 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0028_patient_patientprogrammodel_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator])),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
