# Generated by Django 4.2.4 on 2023-09-06 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
        ('dynamic_models', '0029_tempprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBenefitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('active', 'Active'), ('shortfall', 'Document Shortfall'), ('complete', 'Completed'), ('suspend', 'Suspended')], default='applied', max_length=200, verbose_name='Benefit Status')),
                ('credits', models.BigIntegerField(null=True, verbose_name='Credits')),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('approved_by', zelthy.apps.dynamic_models.fields.ZForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.appusermodel')),
                ('benefit', zelthy.apps.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.benefitsmodel')),
                ('program', zelthy.apps.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.patientprogrammodel')),
                ('suspended_by', zelthy.apps.dynamic_models.fields.ZForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefit_suspended_by', to='appauth.appusermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
