# Generated by Django 4.2.4 on 2023-09-06 09:47

from django.db import migrations
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0031_ordermodel_patient_benefit_alter_patient_city_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='patient_benefit',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_benefit_orders', to='dynamic_models.patientbenefitmodel'),
        ),
    ]
