# Generated by Django 4.2.4 on 2023-09-06 11:13

from django.db import migrations, models
# import pluginbase._internalspace._sp4da422300dac10c4103a92bcc0f1bdc4.test_module.models
from ..test_module.models import age_validator


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0032_alter_ordermodel_patient_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempprofile',
            name='age',
            field=models.IntegerField(validators=[age_validator]),
        ),
    ]
