# Generated by Django 4.2.4 on 2023-09-06 11:49

from django.db import migrations, models
# import pluginbase._internalspace._sp16e8fff32826d610dee7325f9e3e7a78.order_module.models
# import pluginbase._internalspace._sp16e8fff32826d610dee7325f9e3e7a78.test_module.models

from ..order_module.models import random_unique_code
from ..test_module.models import age_validator


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0033_alter_tempprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='ordercode',
            field=models.CharField(default=random_unique_code, max_length=6, verbose_name='Order Code'),
        ),
        migrations.AlterField(
            model_name='tempprofile',
            name='age',
            field=models.IntegerField(validators=[age_validator]),
        ),
    ]
