# Generated by Django 4.2.4 on 2023-09-06 11:58

from django.db import migrations, models
# import pluginbase._internalspace._spa00b5b2f4a34e64e1103cf0dd50e0176.order_module.models
# import pluginbase._internalspace._spa00b5b2f4a34e64e1103cf0dd50e0176.test_module.models

from ..order_module.models import random_unique_code, qty_validator
from ..test_module.models import age_validator


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0034_alter_ordermodel_ordercode_alter_tempprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.IntegerField(default=4, validators=[qty_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='ordercode',
            field=models.CharField(default=random_unique_code, max_length=6, verbose_name='Order Code'),
        ),
        migrations.AlterField(
            model_name='tempprofile',
            name='age',
            field=models.IntegerField(validators=[age_validator]),
        ),
    ]
