# Generated by Django 4.2.4 on 2023-09-06 12:00

from django.db import migrations, models
# import pluginbase._internalspace._sp7a3de8ad48966a536519ddee7c25acaf.order_module.models
# import pluginbase._internalspace._sp7a3de8ad48966a536519ddee7c25acaf.test_module.models

from ..order_module.models import random_unique_code, qty_validator
from ..test_module.models import age_validator


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0035_ordermodel_quantity_alter_ordermodel_ordercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='ordercode',
            field=models.CharField(default=random_unique_code, max_length=6, verbose_name='Order Code'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='quantity',
            field=models.IntegerField(validators=[qty_validator]),
        ),
        migrations.AlterField(
            model_name='tempprofile',
            name='age',
            field=models.IntegerField(validators=[age_validator]),
        ),
    ]
