# Generated by Django 4.2.4 on 2023-09-06 12:27

from django.db import migrations, models
import pluginbase._internalspace._sp2013f5a451c30e7982c73911086dfec7.order_module.models
import pluginbase._internalspace._sp2013f5a451c30e7982c73911086dfec7.test_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0037_alter_ordermodel_ordercode_alter_ordermodel_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='ordercode',
            field=models.CharField(default=pluginbase._internalspace._sp2013f5a451c30e7982c73911086dfec7.order_module.models.random_unique_code, max_length=6, verbose_name='Order Code'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='quantity',
            field=models.IntegerField(validators=[pluginbase._internalspace._sp2013f5a451c30e7982c73911086dfec7.order_module.models.qty_validator]),
        ),
        migrations.AlterField(
            model_name='tempprofile',
            name='age',
            field=models.IntegerField(validators=[pluginbase._internalspace._sp2013f5a451c30e7982c73911086dfec7.test_module.models.age_validator]),
        ),
    ]
