# Generated by Django 4.2.16 on 2026-05-28 10:32

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zango.core.storage_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], db_index=True, max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('file', zango.core.storage_utils.ZFileField(max_length=512, upload_to=zango.core.storage_utils.RandomUniqueFileName, validators=[zango.core.storage_utils.validate_file_extension])),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'code_execution_run_file',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snippet_version', models.PositiveIntegerField()),
                ('source_snapshot', models.TextField()),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timed out'), ('aborted', 'Aborted')], db_index=True, default='queued', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('return_value', models.JSONField(blank=True, null=True)),
                ('return_value_truncated', models.BooleanField(default=False)),
                ('exception_type', models.CharField(blank=True, default='', max_length=128)),
                ('exception_message', models.TextField(blank=True, default='')),
                ('exception_traceback', models.TextField(blank=True, default='')),
                ('triggered_by', models.CharField(blank=True, default='', max_length=255)),
                ('trigger_kind', models.CharField(choices=[('ui_run', 'Run from UI'), ('ui_save_run', 'Save & Run from UI'), ('api', 'API'), ('retry', 'Retry')], default='ui_run', max_length=16)),
            ],
            options={
                'db_table': 'code_execution_run',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('code', models.TextField(default='')),
                ('code_hash', models.CharField(blank=True, default='', max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'code_execution_snippet',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSnippetFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', zango.core.storage_utils.ZFileField(max_length=512, upload_to=zango.core.storage_utils.RandomUniqueFileName, validators=[zango.core.storage_utils.validate_file_extension])),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='code_execution.codesnippet')),
            ],
            options={
                'db_table': 'code_execution_snippet_file',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='codesnippet',
            index=models.Index(fields=['is_archived', '-modified_at'], name='code_execut_is_arch_3df88c_idx'),
        ),
        migrations.AddField(
            model_name='codeexecution',
            name='snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='code_execution.codesnippet'),
        ),
        migrations.AddField(
            model_name='codeexecfile',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='code_execution.codeexecution'),
        ),
        migrations.AddField(
            model_name='codeexecfile',
            name='source_snippet_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='code_execution.codesnippetfile'),
        ),
        migrations.AddIndex(
            model_name='codesnippetfile',
            index=models.Index(fields=['snippet', 'name'], name='code_execut_snippet_c0bd7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='codesnippetfile',
            constraint=models.UniqueConstraint(fields=('snippet', 'name'), name='codexec_snippetfile_unique_name'),
        ),
        migrations.AddIndex(
            model_name='codeexecution',
            index=models.Index(fields=['snippet', '-queued_at'], name='code_execut_snippet_5a8225_idx'),
        ),
        migrations.AddIndex(
            model_name='codeexecution',
            index=models.Index(fields=['status', '-queued_at'], name='code_execut_status_56a8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='codeexecfile',
            index=models.Index(fields=['execution', 'kind'], name='code_execut_executi_3d7079_idx'),
        ),
        migrations.AddIndex(
            model_name='codeexecfile',
            index=models.Index(fields=['execution', 'kind', 'name'], name='code_execut_executi_3fa951_idx'),
        ),
        migrations.AddConstraint(
            model_name='codeexecfile',
            constraint=models.UniqueConstraint(fields=('execution', 'kind', 'name'), name='codexec_execfile_unique_name'),
        ),
    ]
