# Generated by Django 4.2.16 on 2026-05-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_execution', '0002_initial_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecutionLogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('out', 'stdout'), ('err', 'stderr'), ('info', 'INFO'), ('warn', 'WARN'), ('sys', 'system')], max_length=8)),
                ('message', models.TextField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_lines', to='code_execution.codeexecution')),
            ],
            options={
                'db_table': 'code_execution_log_line',
                'ordering': ['execution', 'seq'],
                'indexes': [models.Index(fields=['execution', 'seq'], name='code_execut_executi_13d386_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='codeexecutionlogline',
            constraint=models.UniqueConstraint(fields=('execution', 'seq'), name='codexec_logline_unique_seq'),
        ),
    ]
