# Generated by Django 4.2.16 on 2026-09-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentModeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(default='anthropic', max_length=16)),
                ('config_encrypted', models.BinaryField(blank=True, null=True)),
                ('default_model', models.CharField(blank=True, default='', max_length=64)),
                ('default_effort', models.CharField(blank=True, default='', max_length=16)),
                ('max_run_seconds', models.PositiveIntegerField(default=1800)),
                ('max_turns', models.PositiveIntegerField(blank=True, null=True)),
                ('max_budget_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('monthly_budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agent Mode settings',
                'verbose_name_plural': 'Agent Mode settings',
                'db_table': 'agent_mode_platform_settings',
            },
        ),
    ]
