# Generated by Django 4.2.16 on 2026-09-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_mode_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodesettings',
            name='allow_frontend_build',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentmodesettings',
            name='analyst_budget_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agentmodesettings',
            name='analyst_effort',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='agentmodesettings',
            name='analyst_max_turns',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmodesettings',
            name='analyst_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agentmodesettings',
            name='ensure_packages',
            field=models.BooleanField(default=True),
        ),
    ]
