# Generated by Django 4.2.5 on 2023-09-19 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import zelthy.apps.permissions.mixin
import zelthy.core.storage_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0002_alter_policymodel_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('name', models.CharField(max_length=75, verbose_name='full name of user')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='mobile number')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address_line_1', models.CharField(blank=True, max_length=255, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('address_line_3', models.CharField(blank=True, max_length=255, verbose_name='address line 3')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='state')),
                ('pincode', models.CharField(blank=True, max_length=20, verbose_name='pincode/zipcode')),
                ('country', models.CharField(max_length=200, null=True, verbose_name='country')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=zelthy.core.storage_utils.RandomUniqueFileName, verbose_name='user profile pic')),
                ('extra_data', models.JSONField(null=True)),
                ('policies', models.ManyToManyField(related_name='user_policies', to='permissions.policymodel')),
                ('policy_groups', models.ManyToManyField(related_name='user_policy_groups', to='permissions.policygroupmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, zelthy.apps.permissions.mixin.PermissionMixin),
        ),
        migrations.CreateModel(
            name='UserRoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Unique Name of the User Role')),
                ('config', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('policies', models.ManyToManyField(blank=True, related_name='role_policies', to='permissions.policymodel')),
                ('policy_groups', models.ManyToManyField(blank=True, related_name='role_policy_groups', to='permissions.policygroupmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, zelthy.apps.permissions.mixin.PermissionMixin),
        ),
        migrations.CreateModel(
            name='OldPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=300)),
                ('password_date', models.DateField(auto_now_add=True, verbose_name='Password Change Date')),
                ('password_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Password Change DateTime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appusermodel',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='appauth.userrolemodel'),
        ),
    ]
