# Generated by Django 4.2.4 on 2023-08-23 10:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("appauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appusermodel",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="mobile number",
            ),
        ),
    ]
