# Generated by Django 4.2.4 on 2023-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appauth", "0002_appusermodel_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrolemodel",
            name="temp_field",
        ),
        migrations.AddField(
            model_name="userrolemodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
