# Generated by Django 4.2.4 on 2023-09-10 18:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("appauth", "0002_default_user_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrolemodel",
            name="temp_field",
        ),
        migrations.AddField(
            model_name="appusermodel",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="mobile number",
            ),
        ),
        migrations.AddField(
            model_name="userrolemodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="appusermodel",
            name="roles",
            field=models.ManyToManyField(
                related_name="users", to="appauth.userrolemodel"
            ),
        ),
    ]
