# Generated by Django 4.2.4 on 2023-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appauth", "0003_remove_userrolemodel_temp_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appusermodel",
            name="roles",
            field=models.ManyToManyField(
                related_name="users", to="appauth.userrolemodel"
            ),
        ),
    ]
