# Generated by Django 4.2.4 on 2023-09-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "appauth",
            "0003_remove_userrolemodel_temp_field_appusermodel_mobile_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OldPasswords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=300)),
                (
                    "password_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Password Change Date"
                    ),
                ),
                (
                    "password_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Password Change DateTime",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
