# Generated by Django 4.2.4 on 2023-09-08 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="themesmodel",
            old_name="is_default",
            new_name="is_active",
        ),
    ]
