# Generated by Django 4.2.11 on 2024-09-13 08:18

from django.db import migrations
import zango.core.storage_utils


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_tenantmodel_fav_icon_alter_tenantmodel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmodel',
            name='app_template',
            field=zango.core.storage_utils.ZFileField(blank=True, null=True, upload_to=zango.core.storage_utils.RandomUniqueFileName, validators=[zango.core.storage_utils.validate_file_extension], verbose_name='template used for app'),
        ),
    ]
