# Generated by Django 4.2.16 on 2025-08-14 05:52

from django.db import migrations, models
import zango.apps.shared.tenancy.schema


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_tenantmodel_app_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmodel',
            name='auth_config',
            field=models.JSONField(default=zango.apps.shared.tenancy.schema.get_default_auth_config),
        ),
    ]
