# Generated by Django 4.2.16 on 2025-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_tenantmodel_app_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmodel',
            name='auth_config',
            field=models.JSONField(default={'login_methods': {'allowed_usernames': ['email', 'mobile'], 'oidc': {'enabled': False}, 'otp': {'enabled': False}, 'password': {'enabled': True, 'forgot_password_enabled': True, 'password_reset_link_expiry_hours': 24}, 'sso': {'enabled': False}}, 'password_policy': {'allow_change': True, 'min_length': 8, 'password_expiry_days': 90, 'password_history_count': 3, 'require_lowercase': True, 'require_numbers': True, 'require_special_chars': False, 'require_uppercase': True, 'reset': {'enabled': True, 'expiry_hours': 2, 'method': ['email']}}, 'session_policy': {'force_logout_on_password_change': True, 'max_concurrent_sessions': 0}, 'two_factor_auth': {'required': False}}),
        ),
    ]
