# Generated by Django 4.2.16 on 2026-07-14 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zango.core.storage_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platformauth', '0002_platformusermodel_is_superadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('object_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('app_users', 'App Users'), ('access_logs', 'Access Logs'), ('audit_logs_app', 'Application Audit Logs'), ('audit_logs_framework', 'Framework Audit Logs')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('filters_summary', models.CharField(blank=True, default='', max_length=512)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('file', zango.core.storage_utils.ZFileField(blank=True, null=True, upload_to=zango.core.storage_utils.RandomUniqueFileName, validators=[zango.core.storage_utils.validate_file_extension])),
                ('filename', models.CharField(blank=True, default='', max_length=256)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platformauth.platformusermodel')),
            ],
            options={
                'db_table': 'exports_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='exports_job_request_b3cf99_idx'), models.Index(fields=['kind', 'status'], name='exports_job_kind_865a01_idx')],
            },
        ),
    ]
