# Generated by Django 4.2.15 on 2025-04-30 06:44

import django.core.validators
from django.db import migrations, models
import zango.core.encrypted_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('key', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][a-z0-9_]*$', 'No Space, First Character Caps, No Special Character except _ allowed in Secret key')], verbose_name='Secret key')),
                ('value', zango.core.encrypted_fields.EncryptedTextField(blank=True, verbose_name='Secret Value')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(zango.core.encrypted_fields.ZEncryptedFieldMixin, models.Model),
        ),
    ]
