# Generated by Django 4.2.4 on 2023-08-23 10:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("platformauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformusermodel",
            name="is_superadmin",
            field=models.BooleanField(
                default=False,
                help_text="Is user Super Admin?",
                verbose_name="Super Admin",
            ),
        ),
        migrations.AddField(
            model_name="platformusermodel",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="mobile number",
            ),
        ),
    ]
