# Generated by Django 4.2.2 on 2023-08-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address_1',
            field=models.ManyToManyField(to='dynamic_models.address'),
        ),
    ]
