# Generated by Django 4.2.2 on 2023-08-05 12:00

from django.db import migrations, models
import django.db.models.deletion
import zelthy3.backend.apps.tenants.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0002_patient_address_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagemodel',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=zelthy3.backend.apps.tenants.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_1',
            field=zelthy3.backend.apps.tenants.dynamic_models.fields.ZManyToManyField(to='dynamic_models.address'),
        ),
    ]
