# Generated by Django 4.2.2 on 2023-08-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0002_property_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='values',
        ),
    ]
