# Generated by Django 4.2.2 on 2023-08-14 14:23

from django.db import migrations
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0003_remove_property_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='values',
            field=zelthy.apps.dynamic_models.fields.ZManyToManyField(to='dynamic_models.propertyvalue'),
        ),
    ]
