# Generated by Django 4.2.2 on 2023-08-14 15:35

from django.db import migrations
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_property_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='values',
        ),
        migrations.AddField(
            model_name='property',
            name='pg',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.landingpagemodel'),
        ),
    ]
