# Generated by Django 4.2.4 on 2023-08-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0006_property_values'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address1',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='system_info',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.RemoveField(
            model_name='npost',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='property',
            name='item',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pg',
        ),
        migrations.RemoveField(
            model_name='property',
            name='value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='values',
        ),
        migrations.RemoveField(
            model_name='systeminfo',
            name='system_details',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='LandingPageModel',
        ),
        migrations.DeleteModel(
            name='NPost',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyValue',
        ),
        migrations.DeleteModel(
            name='SystemDetails',
        ),
        migrations.DeleteModel(
            name='SystemInfo',
        ),
    ]
