# Generated by Django 4.2.5.dev20230804160846 on 2023-08-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0006_property_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='values',
        ),
    ]
