# Generated by Django 4.2.5.dev20230804160846 on 2023-09-01 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0002_default_user_roles'),
        ('dynamic_models', '0010_remove_address1_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address1',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='address1',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='address1',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='forum',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='instance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='instance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='item',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='landingpagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingpagemodel',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='landingpagemodel',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='landingpagemodel',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='npost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npost',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='npost',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='npost',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='property',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='property',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='systemdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemdetails',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='systemdetails',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='systemdetails',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
        migrations.AddField(
            model_name='tag',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='modified_by',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel'),
        ),
    ]
