# Generated by Django 4.2.16 on 2026-07-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appllmprovidermodel',
            name='pricing_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual override'), ('aws_live', 'AWS live pricing')], help_text="Where the cost overrides came from. 'manual' is never overwritten by automated pricing refresh; 'aws_live' is refreshed automatically.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appllmprovidermodel',
            name='rates_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the cost overrides were last updated by an automated pricing refresh.', null=True),
        ),
    ]
