# Generated by Django 4.2.16 on 2026-03-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appllminvocation',
            new_name='ai_appllmin_provide_fdec95_idx',
            old_name='ai_appllminv_provide_idx',
        ),
        migrations.RenameIndex(
            model_name='appllminvocation',
            new_name='ai_appllmin_status_39f2e9_idx',
            old_name='ai_appllminv_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appllminvocation',
            new_name='ai_appllmin_created_0602e1_idx',
            old_name='ai_appllminv_created_idx',
        ),
    ]
