# Generated by Django 4.2.16 on 2026-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_tools'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appllmagent',
            name='ai_agent_provider_idx',
        ),
        migrations.RemoveIndex(
            model_name='appllmagent',
            name='ai_agent_enabled_idx',
        ),
        migrations.RemoveIndex(
            model_name='appllmpromptversion',
            name='ai_promptver_prompt_ver_idx',
        ),
        migrations.RemoveIndex(
            model_name='appllmpromptversion',
            name='ai_promptver_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appllminvocation',
            new_name='ai_appllmin_agent_i_05a7bc_idx',
            old_name='ai_appllminv_agent_idx',
        ),
        migrations.RenameIndex(
            model_name='appllmtool',
            new_name='ai_appllmto_is_acti_ea744c_idx',
            old_name='ai_tool_active_section_idx',
        ),
        migrations.RenameIndex(
            model_name='appllmtool',
            new_name='ai_appllmto_name_7e53f7_idx',
            old_name='ai_tool_name_idx',
        ),
        migrations.RenameIndex(
            model_name='appllmtoolcall',
            new_name='ai_appllmto_invocat_a5cba3_idx',
            old_name='ai_toolcall_inv_round_idx',
        ),
        migrations.RenameIndex(
            model_name='appllmtoolcall',
            new_name='ai_appllmto_tool_na_a0236e_idx',
            old_name='ai_toolcall_name_idx',
        ),
        migrations.RenameIndex(
            model_name='appllmtoolcall',
            new_name='ai_appllmto_status_f21318_idx',
            old_name='ai_toolcall_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appllmtoolconfirmation',
            new_name='ai_appllmto_status_a7ac61_idx',
            old_name='ai_confirm_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appllmtoolconfirmation',
            new_name='ai_appllmto_status_c3c6cf_idx',
            old_name='ai_confirm_expiry_idx',
        ),
        migrations.AddField(
            model_name='appllmagent',
            name='output_json_schema',
            field=models.JSONField(blank=True, help_text='JSON Schema definition for structured output when output_schema is JSON', null=True),
        ),
    ]
