name: End to End Cypress Test

on:
  push:
    branches:
      - cypress/e2e-tests
    # paths:
    #   - "frontend/**"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up zango project with latest zango build
      - name: Setup latest zango project
        uses: ./.github/actions/zango-project-setup-action
        with:
          platform_username: platform_admin@zango.dev
          platform_user_password: Zango@123
          project_name: zango_project
          postgres_user: zango_admin
          postgres_password: zangopass
          postgres_db: zango
          platform_domain_url: localhost
          domain_config_path: ./e2e-tests/local_domains.txt

      # Step 3: Setup Node
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 4: Install dependencies
      - name: Install cypress dependencies
        run: npm install
        working-directory: e2e-tests

      # Step 5: Run Cypress tests and record results
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.5.0
        with:
          working-directory: e2e-tests
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        continue-on-error: true

      # Step 6: Generate Cucumber HTML Report
      - name: Generate Cucumber HTML Report
        run: |
          echo "Running cucumber-html-report.js"
          ls -la
          node cucumber-html-report.js
        working-directory: e2e-tests

      # Step 7: Upload Cypress screenshots on failure
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: e2e-tests/cypress/screenshots
          if-no-files-found: ignore

      # Step 8: Upload Cypress videos
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: e2e-tests/cypress/videos
          if-no-files-found: ignore

      # Step 9: Upload Cucumber HTML Report
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: e2e-tests/reports/cucumber-html-report.html
          if-no-files-found: ignore
