---
name: Renovate
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
  push: null
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.4
        env:
          - name: LOG_LEVEL
            value: debug
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
