name: Ruff
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
      - feat/pre_commit_and_linting
    paths-ignore:
      - 'docs/**'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
